src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Products", mappedBy="productCategory")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setProductCategory($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getProductCategory() === $this) {
                $product->setProductCategory(null);
            }
        }

        return $this;
    }
    public function __toString() {
        return $this->name;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductsRepository")
 */
class Products
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ProductName;

    /**
     * @ORM\Column(type="text")
     */
    private $ProductDescription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ProductImage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ProductMaker;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $productCategory;

    /**
     * @ORM\Column(type="float")
     */
    private $ProductPrice;

    /**
     * @ORM\Column(type="float")
     */
    private $Tax;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->ProductName;
    }

    public function setProductName(string $ProductName): self
    {
        $this->ProductName = $ProductName;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->ProductDescription;
    }

    public function setProductDescription(string $ProductDescription): self
    {
        $this->ProductDescription = $ProductDescription;

        return $this;
    }

    public function getProductImage(): ?string
    {
        return $this->ProductImage;
    }

    public function setProductImage(string $ProductImage): self
    {
        $this->ProductImage = $ProductImage;

        return $this;
    }

    public function getProductMaker(): ?string
    {
        return $this->ProductMaker;
    }

    public function setProductMaker(string $ProductMaker): self
    {
        $this->ProductMaker = $ProductMaker;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProductCategory(): ?Category
    {
        return $this->productCategory;
    }

    public function setProductCategory(?Category $productCategory): self
    {
        $this->productCategory = $productCategory;

        return $this;
    }

    public function getProductPrice(): ?float
    {
        return $this->ProductPrice;
    }

    public function setProductPrice(float $ProductPrice): self
    {
        $this->ProductPrice = $ProductPrice;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->Tax;
    }

    public function setTax(float $Tax): self
    {
        $this->Tax = $Tax;

        return $this;
    }
}

src/Controller/CatalogController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Products;
use App\Repository\ProductsRepository;


class CatalogController extends AbstractController
{
    /**
     * @Route("/catalog", name="catalog")
     */
    public function index(ProductsRepository $repo)   
    {
        $productsList =$repo->findAll();
        return $this->render('catalog/index.html.twig', [
            'controller_name' => 'CatalogController',
            'category_name' => 'Canapés',
            'store_name' => 'Bi-canapés, salons fauteuils , ameublement Lille ',
            'productsList'=> $productsList
        ]);
    }
     /**
     * @Route("catalog/show/product/{id}", name="show_product")
     */
    public function show(Products $product)
    {
             return $this->render('show_product/index.html.twig', [
            'item'=> $product,
            'store_name' => 'Bi-canapés, salons fauteuils , ameublement Lille '
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\CmsPages;
use App\Repository\CmsPagesRepository;

class ContactController extends AbstractController
{
    /**
     * @Route("/contact", name="contact")
     */
    public function index(CmsPagesRepository $repo)
    {        
        $pageContent = $repo->findOneBy(['CmsCategory'=>'contact']);
        return $this->render('contact/index.html.twig', [
            'controller_name' => 'ContactController',
            'content' => $pageContent
        ]);
    }
}

src/Controller/PageAccueilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Products;

class PageAccueilController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $repo = $this->getDoctrine()->getRepository(Products :: class);
        $productsList =$repo->findAll();

        return $this->render('page_accueil/index.html.twig', [
            'controller_name' => 'PageAccueilController',
            'pageTitle' => 'Un grand choix de canapés et salons adapté à votre budget',
            'intro' => 'Pour partager des moments agréables entre amis ou en famille, un canapé confortable est indispensable',
            'productsList'=> $productsList
        ]);
    }

   
}

src/Controller/ShowProductController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ShowProductController extends AbstractController
{
    
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}  <link rel="stylesheet" href="/build/app.css"> {% endblock %}
    </head>
    <body>            
        {% include 'header.html.twig'  %} 
        {% include 'breadcrumb.html.twig'  %} 
       
        <main role="main"> 
            {% block body %}{% endblock %}
            {% include 'footer.html.twig'  %}
        </main> 
            {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <!-- Renders app.js & a webpack runtime.js file
                <script src="/build/runtime.js"></script>
                <script src="/build/app.js"></script> -->
            {% endblock %}
    </body>
</html>

templates/breadcrumb.html.twig
<ul class="breadcrumb">
    <li><a href="{{path('home')}}">Accueil</a></li>
    <li><a href="{{path('catalog')}}">Catalogue</a></li>
</ul>

templates/catalog/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<div class="container">    
{% if productsList|length > 0 %}
<section class="row"><p>Il y a {{ productsList|length}} produit(s) dans la categorie <em>{{ category_name }}</em></p></section>
<div class="row">
{% for item in productsList %}
   <article class="col-4">
       <figure>
           <img src="{{item.productImage}}" alt="{{item.productName}}}" class="img-fluid">
       </figure>
       <h3 class="a-productName">{{item.productName}}</h3>
       <span class="a-productMaker">{{item.productMaker}}</span>
      <p class="a-productDescription">{{item.productDescription}}</p>
      <a href="{{ path('show_product', {'id' : item.id} ) }}">Voir le produit</a>
   </article>
   {% endfor %}
</div>
   {% else %}
   <section class="col-12"><p>Il ny a pas de produits </p></section>
   {% endif %}
</div>
{% endblock %}

templates/catalog/preview.html.twig
   {% for item in productsList %}
   <article class="col-4">
       <figure>
           <img src="{{item.productImage}}" alt="{{item.productName}}}" class="img-fluid">
       </figure>
       <h3 class="a-productName">{{item.productName}}</h3>
       <span class="a-productMaker">{{item.productMaker}}</span>
      <p class="a-productDescription">{{item.productDescription}}</p>
      <a href="{{ path('show_product', {'id' : item.id} ) }}">Voir le produit</a>
   </article>
   {% endfor %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}

<div class="container">
    <article class="row">
        <h1>{{content.name}}</h1>
        {{content.content | raw}}    
    </article>
</div>
{% endblock %}

templates/footer.html.twig
<footer class="container">
    <h3> I'm the footer</h3>
</footer>

templates/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Bi-canapés</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ path('home') }}"> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ path('catalog') }}">Canapés et salons</a>
            </li>            
            <li class="nav-item">
              <a class="nav-link" href="{{ path('contact') }}">Localisation et contact</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

templates/page_accueil/carousel/carousel.html.twig
<div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1" class=""></li>
          <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="../../../public/media/images/carousel/canap1.jpg" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

templates/page_accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
    
<div class="container">
        {% include 'page_accueil/carousel/carousel.html.twig' %}
        
        <article class="row">
            <h1 class="a-title">{{ pageTitle }}</h1>
            <p class="a-intro">{{ intro }}</p>
        </article>
    
    <section class="row">{% include 'catalog/preview.html.twig' %}</section>
</div>

{% endblock %}

templates/show_product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{store_name}} - {{item.productName}} {% endblock %}

{% block body %}
<article class="col-12">
    <figure>
        <img src="{{item.productImage}}" alt="{{item.productName}}}" class="img-fluid">
    </figure>
    <h3 class="a-productName">{{item.productName}}</h3>
    <span class="a-productMaker">{{item.productMaker}}</span>
   <p class="a-productDescription">{{item.productDescription}}</p>
</article>
{% endblock %}